# Generated by Django 3.2.17 on 2023-06-25 19:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0007_auto_20230620_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('last_upload', models.DateTimeField(null=True)),
                ('mdb_source_id', models.CharField(blank=True, max_length=32)),
                ('location_country_code', models.CharField(blank=True, max_length=32)),
                ('location_subdivision_name', models.CharField(blank=True, max_length=100)),
                ('location_municipality', models.CharField(blank=True, max_length=100)),
                ('provider', models.CharField(blank=True, max_length=250)),
                ('urls_direct_download', models.CharField(blank=True, max_length=250)),
                ('urls_authentication_type', models.CharField(blank=True, max_length=100)),
                ('urls_authentication_info', models.CharField(blank=True, max_length=100)),
                ('urls_api_key_parameter_name', models.CharField(blank=True, max_length=100)),
                ('urls_latest', models.CharField(blank=True, max_length=250)),
                ('urls_license', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='agency',
            name='data_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transit.datasource'),
        ),
    ]
