# Generated by Django 3.2.17 on 2023-06-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0008_add_data_source_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='last_upload_status',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='agency',
            name='agency_lang',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='agency',
            name='agency_phone',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
