#!/bin/bash

set -e

if [[ -n "${EBUSTRANSIT_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0") Run a batch process
"
}


if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else 
        docker compose --env-file .env run --rm --build batch-upload process_upload.py "$@"
    fi
fi